CREATE DATABASE IF NOT EXISTS mini_app;
USE app;

CREATE TABLE produits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    dsp VARCHAR(100)NOT NULL,
    prix DECIMAL(10) NOT NULL
);
